import Header from '@app/components/Common/Header';
import ListView from '@app/components/Common/ListView';
import PageTitle from '@app/components/Common/PageTitle';
import useDiscover from '@app/hooks/useDiscover';
import defineMessages from '@app/utils/defineMessages';
import type { MovieResult, TvResult } from '@server/models/Search';
import { useIntl } from 'react-intl';

const messages = defineMessages('components.Discover', {
  airecommendations: 'Recommended for You',
  airecommendationsDescription:
    'Personalized picks generated by AI based on your request history, watchlist, and library.',
  empty:
    'No AI recommendations yet. Recommendations are generated periodically — check back soon, or trigger them from Settings → Jobs & Cache.',
});

const AiRecommendations = () => {
  const intl = useIntl();
  const {
    isLoadingInitialData,
    isEmpty,
    isLoadingMore,
    isReachingEnd,
    titles,
    fetchMore,
  } = useDiscover<MovieResult | TvResult>(
    '/api/v1/discover/ai-recommendations'
  );

  return (
    <>
      <PageTitle title={intl.formatMessage(messages.airecommendations)} />
      <div className="mb-5 mt-1">
        <Header>{intl.formatMessage(messages.airecommendations)}</Header>
        <p className="mt-2 text-sm text-gray-500">
          {intl.formatMessage(messages.airecommendationsDescription)}
        </p>
      </div>
      <ListView
        items={titles}
        isEmpty={isEmpty}
        isLoading={
          isLoadingInitialData || (isLoadingMore && (titles?.length ?? 0) === 0)
        }
        isReachingEnd={isReachingEnd}
        onScrollBottom={fetchMore}
      />
    </>
  );
};

export default AiRecommendations;
