import Header from '@app/components/Common/Header';
import LoadingSpinner from '@app/components/Common/LoadingSpinner';
import PageTitle from '@app/components/Common/PageTitle';
import AiRecommendationCard from '@app/components/Discover/AiRecommendationCard';
import useDiscover from '@app/hooks/useDiscover';
import defineMessages from '@app/utils/defineMessages';
import type { MovieResult, TvResult } from '@server/models/Search';
import { useMemo, useState } from 'react';
import { useIntl } from 'react-intl';

const messages = defineMessages('components.Discover', {
  airecommendations: 'Recommended for You',
  airecommendationsDescription:
    'Personalized picks generated by AI based on your request history, watchlist, and library. Rate them to improve future suggestions.',
  empty:
    'No AI recommendations yet. Recommendations are generated periodically — check back soon, or trigger them from Settings → Jobs & Cache.',
});

const AiRecommendations = () => {
  const intl = useIntl();
  const { isLoadingInitialData, isEmpty, titles } = useDiscover<
    MovieResult | TvResult
  >('/api/v1/discover/ai-recommendations');

  // Track locally-dismissed cards (dislike/seen) so they vanish immediately
  // without waiting for the next generation run to filter them out.
  const [removed, setRemoved] = useState<Set<number>>(new Set());

  const visible = useMemo(
    () => (titles ?? []).filter((t) => !removed.has(t.id)),
    [titles, removed]
  );

  const handleRemove = (tmdbId: number) => {
    setRemoved((prev) => {
      const next = new Set(prev);
      next.add(tmdbId);
      return next;
    });
  };

  const showEmpty = isEmpty || (!isLoadingInitialData && visible.length === 0);

  return (
    <>
      <PageTitle title={intl.formatMessage(messages.airecommendations)} />
      <div className="mb-5 mt-1">
        <Header>{intl.formatMessage(messages.airecommendations)}</Header>
        <p className="mt-2 text-sm text-gray-500">
          {intl.formatMessage(messages.airecommendationsDescription)}
        </p>
      </div>
      {isLoadingInitialData && (
        <LoadingSpinner />
      )}
      {showEmpty && !isLoadingInitialData && (
        <div className="mt-16 w-full text-center text-lg text-gray-400">
          {intl.formatMessage(messages.empty)}
        </div>
      )}
      {visible.length > 0 && (
        <ul className="cards-vertical">
          {visible.map((item) => (
            <li key={`${item.id}-${item.mediaType}`}>
              <AiRecommendationCard
                item={item}
                rationale={(item as any).aiRationale}
                onRemove={handleRemove}
              />
            </li>
          ))}
        </ul>
      )}
    </>
  );
};

export default AiRecommendations;
